# Generated by Django 3.2.4 on 2021-07-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_owner_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
