# Generated by Django 3.2.4 on 2021-07-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='host',
            field=models.BooleanField(default=False),
        ),
    ]
