# Generated by Django 3.2.4 on 2021-07-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_playing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
