# Generated by Django 3.2.4 on 2021-07-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_playing',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
