# Generated by Django 3.2.4 on 2021-07-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20210705_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='username',
            new_name='user_name',
        ),
    ]
