# Generated by Django 3.2.4 on 2021-07-05 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_rename_username_player_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
